In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [5]:
data_file = '/Users/usermac/Documents/Education/Data Science/Python Practice/Budgets/2024-Table 1.csv'
df = pd.read_csv(data_file)

In [6]:
df[['Detail','Total Pay','First Pay','Second Pay']].groupby('Detail').sum(['Total Pay','First Pay','Second Pay']).sort_values(by='Total Pay',ascending=False)

                                   Total Pay  First Pay  Second Pay
Detail
Ahorro pa la moto                      34500    16500.0     18000.0
TC Banco de Bogota                     14190      590.0     13600.0
Credito Fondecom (fondegarantias)      10100     5000.0      5100.0
Hipoteca                                7950      300.0      7650.0
Comida                                  7200     3600.0      3600.0
Alquiler                                6592     6592.0         0.0
ðŸ’œðŸ–¤                                      3600        0.0      3600.0
Credito Bancolombia                     3000        0.0      3000.0
Regalos                                 2850     2550.0       300.0
Inverciones Zukaritas                   2400     1200.0      1200.0
MI PAGO (Tyba)                          2200     1100.0      1100.0
Vuelos Brazil                           2000        0.0      2000.0
Calistenia                              1920        0.0      1920.0
Las bendis                              1800        0.0      1800.0
Servicios Jamundi                       1495     1135.0       360.0
Club del 1%                             1200        0.0      1200.0
Salida Teathron (Tyba)                   950      500.0       450.0
Seguro bici                              585      585.0         0.0
Datos                                    518        0.0       518.0
Mantenimiento Bici                       480      480.0         0.0
Ropa                                     470      290.0       180.0
TC AVVILLAS                              392      392.0         0.0
BEPS                                     360      180.0       180.0
Cuadro manifestacion Moto                350        0.0       350.0
Salida BIDS                              300      300.0         0.0
PeluquerÃ­a o belleza                     285      135.0       150.0
Impuestos a la propiedad                 250        0.0       250.0
Higiene personal                         230       90.0       140.0
Asopagos                                 150      150.0         0.0
iCloud                                   144        0.0       144.0
Music                                    108        0.0       108.0
Prestamo Diana                            50       50.0         0.0

In [8]:
max_pay = np.max(df['Total Pay'])
min_pay = np.min(df['Total Pay'])

max_pay_row = df['Detail'][df['Total Pay'] == max_pay].unique()
min_pay_row = df['Detail'][df['Total Pay'] == min_pay].unique()

print(max_pay_row)

['Hipoteca']